### PR TITLE
Modified the project to utilize autotools (autoconf, automake,...) an…

### PR DESCRIPTION
**Pull request by 4z0r**
Hi. 

I've modified the project so that it fully utilizes autotools (autoconf, autoheader,...) and libtoolize. I've also made libcli into a shared libary (I might make asc2c into a static one in due time). 

I've also included the changes to all relevant files from your dev branch (source and doc/extra files), where it seemed reasonable. I did not include any changes to the Makefiles or config.h since those are generated. 

I've also did not know your "bug" address (I do not suspect you'll be receiving bugs to your personal address, but you might as well) so I've put bugs@bunny.com in the configure.ac (change that at your convenience).

I know you've had it planed way down the line, but I'd like to port this fork of hnb to solaris, and autotools help out a lot (especially working the OS part out). 

So if you merge this request, I'll move the code around a bit more, keeping various paltforms / systems in mind (moving everything os specific in separate folders, and common source files respectively). 

My next step after that would be to implement some sort of test (automated within the autotools) for the project.

Make distribution with make dist if you'd like.

./configure && make && make install

enjoy 

Cheers

### CODE REVIEW

**Comment by odb9088** [comment]
I've kept the License part etc... but you should edit the ChangeLog too (copy paste ist), as well as the Authors and News file to your liking. 

fyi: the source compiled just fine on my gentoo box: 

Linux sephiroth 4.8.17-hardened-r2 #1 SMP Wed Jan 10 17:00:42 CET 2018 x86_64 QEMU Virtual CPU version (cpu64-rhel6) GenuineIntel GNU/Linux

**Comment by odb9088** [comment]
I've seen the pull request by curiousbird (UI improvements). 

I could either mind curiousbird improvements and commit them to this request (with credit to him/her of course), or you can merge the UI Improvements and I'll re-fork & rewrite the project anew from that with a new pull request.

**Comment by larrykollar** [comment]
Awesome! I'll check this out and merge it as soon as possible.

I was planning to merge curiousbird's improvements soon (kind of tied up with other stuff this week, and want to slightly modify one thing). I'll try to merge your pull request after that. I have a couple of things I've been working on as well — auto-detecting format of opened files, and shifting to OPML-centric — so I may just declare 2.0 once everything is working right and plunge into UTF-8 support.

Good point about the email address. I'll look into getting a bugs@tines-outliner.org address set up. This is the first time I've had two pull requests come in back to back like this, though, so for now I guess my gmail address would be fine.

**Comment by odb9088** [comment]
Hi. 

Take your time. When you've merged the UI Improvements, write me up. It'll be a matter of minutes to fork that branch and rewrite it for autoconf. 

I'll look into the code in the meantime. I've come across some minor things that I've encountered before with ncurses which are an easy and clean fix. And I'll look into something to run test cases too using the autotools, without the use of highly sofisticated frameworks. 

So I'll keep busy. 

After you've merge curiosbird's request (which seems rather solid at a glance), I'll close this request, and rewrite it from scratch. I'll keep this open until then so you can notify me. 

Cheers

**Pull request merged**
